### ISSUE TITLE
Bug sur les votes

### ISSUE THREAD

**Issue by viktortoli** [Naxxramas-Server/Bug-Tracker#1]
Lorsqu'on clique sur "Voter maintenant", les points de vote sont directement donnés, sans qu'il ne faille voter entièrement. 
Le clic simple sur le lien donne les points, permettant des abus.

**Comment by Naxxramas-Server** [comment]
Un système sera bientôt rajouté pour être programmé pour revenir vers le site pour recevoir les points de votes.
Merci de votre retour.
