### ISSUE TITLE
Bug quête couronne de glace [S'il ne peut pas être détourné]

### ISSUE THREAD

**Issue by Corrupt94** [Naxxramas-Server/Bug-Tracker#11]
Cette [quête](https://fr.wowhead.com/quest=12896/sil-ne-peut-pas-%C3%AAtre-d%C3%A9tourn%C3%A9) est juste trop compliqué à faire en l'état actuelle il faut tué le [Général Plaie-de-lumière](https://fr.wowhead.com/npc=29851/g%C3%A9n%C3%A9ral-plaie-de-lumi%C3%A8re) certains mobs (3 exactement) doivent venir nous aider mais ils se font 2 shots ainsi que mon personnage

**Comment by Naxxramas-Server** [comment]
Le Général Plaie-de-Lumière à vu ses dégâts et ses points de vie réduits afin d'être plus facilement accessible.
