### ISSUE TITLE
Quéte "Trahison" activation non faite.

### ISSUE THREAD

**Issue by Maniaki** [Naxxramas-Server/Bug-Tracker#12]
Quete Trahison : Chercher le crane ne provoque pas l'activation dans la quete.

**To Reproduce** - **Comment reproduire**
Les étapes pour reproduire le bug :
1. Go to Voldrune with the quest "Trahison" (last quest of stephan vadu in zul drak)
2. kill the boss
3. wait for the end of the cinematics
4. search the skull
5. see that your quest didn't activate.
Bonus : 6. use the item you've got and see that the teleportation doesn't work.

Ce qu'il devrait se passer.
Je sais pas je connais pas la quete. mais normalement quand on prend le crane il doit s'activer. ou alors il manque un item que l'on ne loot pas. 

no screenshot available (sorry :'( )

**Comment by Naxxramas-Server** [comment]
La quête est totalement fonctionnelle sur le serveur , il faut aller parler au Suzerain Drakurru afin de se téléporter au sommet et de lancer le combat contre celui-ci.
