### ISSUE TITLE
Azjol Nerub

### ISSUE THREAD

**Issue by Alashandra** [Naxxramas-Server/Bug-Tracker#13]
Les packs de mobs du premier boss ne sont pas link correctement, les packs s'enchaînent trop vite et il est impossible à niveau de stuff d'entrée en héroïque de pouvoir passer l'event.
Les miniboss cécitent et mettent en cocon le tank en boucle

**To Reproduce** - **Comment reproduire**
Les étapes pour reproduire le bug :
1.  aller à Azjol Nerub en héro
2. aggro le tirailleur de gauche (le pack ne suit pas)
3. le tuer, le pack ne vient toujours pas, alors aggro le mob de l'extrême droite 
4. Le temps de le tomber, le premier pack ou celui du centre (aléatoire) arrive

**Expected behavior** - **Ce qu'il devrait se passer**
au lancement d'un mob, seul son pack en entier doit venir et à la mort du dernier mob un second pack arrive
Normalement dans le script original, les liens entre les mobs du pack sont effectifs et les 3 packs sont plus espacés les uns des autres pour éviter l'aggro des 3 d'un coup

Merci de faire le nécessaire

**Comment by Naxxramas-Server** [comment]
Merci pour votre report , il sera analysé sous peu.

**Comment by Naxxramas-Server** [comment]
L'event du premier boss a été retravaillé pour être totalement blizzlike.
