### ISSUE TITLE
Mobs invisibles à Skettis dans la Forêt de Terokkar

### ISSUE THREAD

**Issue by Lwizyan** [Naxxramas-Server/Bug-Tracker#14]
Bonjour,

Dans la zone de Skettis à la Forêt de Terokkar, des Arakoas sont censé être visible via une potion. Les "Grand Prêtre de Skettis perdu dans le temps." Cependant, sans avoir l'effet de cette dernière, les mobs semblent tout de même présent. Donc je rentre en combat MAIS je ne les vois pas. Je prends des dégâts, je ne peux pas fuir car je me fais hébéter sans cesse et je ne peux donc pas me défendre. 

Je ne peux malheureusement pas joindre de screen puisqu'il n'y pas de dégâts visibles. Juste ma vie descends. J'espère avoir pu aider avec mes infos, et espérons que ce ne sera pas trop chiant pour vous de résoudre le problème ^^

**Comment by Naxxramas-Server** [comment]
Merci pour votre report , il sera analysé sous peu.

**Comment by Naxxramas-Server** [comment]
Le problème a été résolu.
