### ISSUE TITLE
[QUETE] [45] [Triage]

### ISSUE THREAD

**Issue by Kumik0** [Naxxramas-Server/Bug-Tracker#15]
**Describe the bug** - **Description du bug**
Lorsque l'on utilise le Bandage de Triage sur un Soldat grièvement blessé et que l'on incante entièrement le sort avant que ce dernier ne décède cela devrais nous le compter comme sauvé, ors parfois celui ci n'est pas sauvé et meurs, ce qui rends la quête infaisable.

**To Reproduce** - **Comment reproduire**
Les étapes pour reproduire le bug :
1. Prendre la quête  [45] [Triage] auprès de "Docteur Gustaf VanHowzen"
2. tenter de faire la quête.
3. constater

**Expected behavior** - **Ce qu'il devrait se passer**
Si l'on réussi a appliquer entièrement le bandage de triage le pnj devrais être sauvé.

**Comment by Naxxramas-Server** [comment]
Suite a divers test effectué , il s'avère que la quête est totalement fonctionnelle , vous ne devez juste pas être assez rapide.
