### ISSUE TITLE
Bug Quetes Descendez les Tous

### ISSUE THREAD

**Issue by Stimp4ck** [Naxxramas-Server/Bug-Tracker#16]
**Describe the bug** - **Description du bug**
Lorsque l'on tue les Proto drake à l'aide des Harpons, ils ne sont pas comptabilisé pour valider la quête

**To Reproduce** - **Comment reproduire**
Les étapes pour reproduire le bug :
1. Prendre la quete Descendez les Tous !
2. Utiliser les harpons à Jothuneim
3. Lancer les harpons sur les protos drake
4. Le compteur ne progresse pas
5. Attendre le repop
6. Le compteur avance

**Expected behavior** - **Ce qu'il devrait se passer**
Comptabilisation des proto-drake tués dès le premier kill

**Screenshots**
If applicable, add screenshots and/or videos to help explain your problem.
Si vous pouvez , rajouteé des screenshots et/ou videos pour expliquer le problème

**Additional context** - **Informations complémentaires**
Bug un peu aléatoire, j'ai l'impression que si les proto drake ne viennent pas juste de repop ils ne sont pas comptabilisés...
En gros si l'on arrive et que les protos drake sont à 1/4 de vie ils ne comptent pas ...

**Comment by Naxxramas-Server** [comment]
Merci pour votre report , le problème sera analysé prochainement.
