### ISSUE TITLE
Quête "Un vol de reconnaissance" - Bassin de Sholazar

### ISSUE THREAD

**Issue by AzuLeCazu** [Naxxramas-Server/Bug-Tracker#17]
**Description du bug**
L'appareil, une fois endommagé, est trop lent pour rejoindre à temps le Terrain d’atterrissage de Rive-du-Lac. De plus, l'appareil n'est pas contrôlable verticalement ce qui, je suppose, empêcherait de le faire atterrir une fois arriver, vu qu'il reste à une trop haute altitude. Aussi l'action button1 est censé heal l'appareil si une fusée touche un ennemi (à voir vidéo).

**Ce qu'il devrait se passer**
J'ai regarder une vidéo YT (lien ci-dessous) et la différence est flagrante. L'appareil va plus vite, est dirigeable verticalement et se soigne en touchant des ennemis.

**Informations complémentaires**
Le lien vient des commentaires sur wowhead : http://youtu.be/bKDuH7VhXj4

**Comment by Naxxramas-Server** [comment]
Cette quête a déjà été report , il suffit juste de faire un déplacement latéral ou vertical pour débloquer tous les mouvements de la machine volante.

**Comment by Naxxramas-Server** [comment]
Duplicate of #2
