### ISSUE TITLE
Warrior: Slam - Swing Timer not paused during cast

### ISSUE THREAD

**Issue by ghost** [Naxxramas-Server/Bug-Tracker#19]
**Describe the bug** - **Description du bug**
While Slam is being cast, the Swing Timer of your next Auto Attack isn't paused.

**To Reproduce** - **Comment reproduire**
1. Track your Swing Timer (addons like Quartz get the job done);
2. Start casting Slam;
3. Notice your Swing Timer isn't paused while Slam is being cast, allowing you to hit with Auto Attack once Slam is done.

**Expected behavior** - **Ce qu'il devrait se passer**
Slam should pause the Swing Timer during its ongoing cast.

http://wowwiki.wikia.com/wiki/Slam -- "Patch 3.0.2 (14-Oct-2008): Slam now suspends the weapon swing timer rather than resetting it."

**Additional context** - **Informations complémentaires**
Use Warrior filter.
Slam IDs (go down to "Slam"): https://wowgaming.altervista.org/aowow/?search=Slam#abilities

**Comment by Naxxramas-Server** [comment]
Thank you for the report , that will be reviewed soon
