### ISSUE TITLE
[QUETE] Bassin de Sholazar -  [Un vol de reconnaissance]

### ISSUE THREAD

**Issue by Kumik0** [Naxxramas-Server/Bug-Tracker#2]
**Describe the bug** - **Description du bug**
Lorsque l'on prends la quête un avion fais un allez retour avec nous a bord, lors du retour le joueur dois guider l'avion vers la piste d'atterrissage, sauf que, on ne peut contrôler l'avion pour l'y emmener.
Ce qui nous empêche d'accomplir la quête.
(Le MJ Enolan a pu le constater par lui même)

**To Reproduce** - **Comment reproduire**
Les étapes pour reproduire le bug :
Prendre la quête et constater le bug.

**Expected behavior** - **Ce qu'il devrait se passer**
https://www.youtube.com/watch?v=bKDuH7VhXj4

**Screenshots**
Tout est dans la vidéo

**Additional context** - **Informations complémentaires**
Rien à ajouter

**Comment by viktortoli** [comment]
La quête n'est pas buguée, il faut bien se placer sur la piste de décollage, c'est un rond noir, le donneur de quête est dessus, et faut spammer
Mais en effet l'avion ne peut pas rester stationnaire donc c'est assez compliqué
J'ai réussi à la faire faut juste bien forcer et spammer quand tu touches le sol avec au milieu de la zone

**Comment by viktortoli** [comment]
Pour reprendre le contrôle de l'avion il faut appuyer sur la barre espace, ca fait monter l'avion et libère les mouvements dans les 3 axes de l'espace de l'avion, CA c'est bugué !

**Comment by Naxxramas-Server** [comment]
La quête sera analysée prochainement

**Comment by Naxxramas-Server** [comment]
La quête est totalement fonctionnelle suite à différents test ,n cependant , en effet l'avion ne reste pas en vol stationnaire si nous ne touchons a rien et il faut donc appuyer sur le bouton 2 qui permet d’atterrir lorsque nous arrivons sur la piste pour rendre la quête , nous verrons ce que nous pourrons faire pour ce léger bug.
