### ISSUE TITLE
Warrior: Charge - faulty and unreliable while falling

### ISSUE THREAD

**Issue by ghost** [Naxxramas-Server/Bug-Tracker#20]
**Describe the bug** - **Description du bug**
Charge (and similar that work the same way -- like Intercept, for example), can't be used while falling.

**To Reproduce** - **Comment reproduire**
1. Be falling;
2. Target something that's standing on some sort of ground and will be within Charge's effective Range (with pathing included);
3. Spam the thing;
4. Notice how it doesn't work ("No path available"), and weep in despair as you fall to your doom.

https://www.youtube.com/watch?v=1gKnusySb9o
https://www.youtube.com/watch?v=rgIrBXmxkDc

**Expected behavior** - **Ce qu'il devrait se passer**
Charge/Intercept etc. should work on Targets while falling (so long as there's pathing and is within effective Range with the necessary pathing accounted for), and should reset the distance you've fallen for taking Fall Damage -- if used just before landing, you can practically cause yourself to take no Fall Damage whatsoever.

https://www.youtube.com/watch?v=jlImCxoqgEQ
https://www.youtube.com/watch?v=vK3IqseGEQE
https://www.youtube.com/watch?v=nD2stcm4W8M&feature=youtu.be&t=166
https://www.youtube.com/watch?v=IijlbG7yrlc&feature=youtu.be&t=181

**Additional context** - **Informations complémentaires**
Some links might be missing due to lack of memory, as this affects every Ability that acts just like Charge -- such as Intercept, Feral Charge - Bear, Felguard's Intercept, and so on.
IDs for affected Abilities:
https://wowgaming.altervista.org/aowow/?search=Charge#abilities
https://wowgaming.altervista.org/aowow/?search=Intercept#abilities
https://wowgaming.altervista.org/aowow/?search=Intervene#abilities

_Edited to add more links on how it's supposed to work._
**Note: It seems to work but _barely_ -- it does if you're just about to touch the surface, and you have to be at a fair distance from your Target to work.
https://youtu.be/4Y1fz-TcRYw -- compare to the first two recorded videos, and then to the provided videos from Retail.
Needs improvements to work as shown in the provided videos.**

**Comment by Naxxramas-Server** [comment]
Thank you for the report , that will be reviewed soon
