### ISSUE TITLE
[Haut fait] Flirter avec le désastre (Event : De l'amour dans l'air)

### ISSUE THREAD

**Issue by AzuLeCazu** [Naxxramas-Server/Bug-Tracker#21]
Bonjour, 

**Description du bug**
Le haut fait "Flirter avec le désastre" ne fonctionne pas. J'ai pourtant suivi toutes les étapes à la lettre et NADA, les 2 objectifs "Embrasser Sraaz" et "Poignée de pétales de rose sur Sraaz" ne se déclenchent pas. J'ai essayé en étant complètement ivre ou juste en étant ivre et ça marche pas. Par contre, je ne sais pas si du côté de la Horde le problème est le même avec le PNJ "Jeremiah Payson".

**Ce qu'il devrait se passer**
Utiliser un parfum, boire une boisson alcoolisée jusqu'à ce qu'on soit complètement ivre (un message le notifiant apparaîtra dans la fenêtre de discussion). Une fois dans cet état, utiliser la Poignée de pétales de rose sur Sraaz (alliance) ou Jeremiah Payson (horde) et faire un /kiss sur ce dernier.

**Vidéo**
https://www.youtube.com/watch?time_continue=9&v=mzc3oWmcM_k

**Comment by Naxxramas-Server** [comment]
Ce HF a été testé plusieurs fois et est totalement fonctionnel.
