### ISSUE TITLE
Haut Fait : "on se sent seul" de l'event de la St Valentin

### ISSUE THREAD

**Issue by Alashandra** [Naxxramas-Server/Bug-Tracker#22]
**Describe the bug** - **Description du bug**
Le panier de pique nique ne s'affiche pas (pas de parasol cliquable)

**To Reproduce** - **Comment reproduire**
Les étapes pour reproduire le bug :
1. Acheter un panier à pique nique aux pnj de l'event
2. Acheter une boite de chocolat pour avoir "délice au lait"
3. Se rendre à Dalaran
4. Grouper un joueur pour partager le pique nique
5. cliquer sur le panier
6. Voyez que rien ne s'affiche

**Expected behavior** - **Ce qu'il devrait se passer**
en étape 6 un parasol et une nappe devraient apparaitre pour que les 2 joueurs puissent cliquer dessus, manger leur chocolat et voilà le haut fait

**Screenshots**
If applicable, add screenshots and/or videos to help explain your problem.
Si vous pouvez , rajouteé des screenshots et/ou videos pour expliquer le problème

**Additional context** - **Informations complémentaires**
Add any other context about the problem here. (database link , etc ...)
Rajoutez des informations complémentaires sur le problème (lien base de donnée , etc...)

**Comment by AzuLeCazu** [comment]
Yop,
Je complète ton post.
**Vidéo**
https://www.youtube.com/watch?time_continue=9&v=Xz1UGyaeY3Y
A la 38ème seconde, on peut remarquer que quand 2 personnes cliquent sur le pique-nique, ça donne un buff. Je pense que c'est à ce moment là qu'il faut manger le délice au lait.

**Comment by Naxxramas-Server** [comment]
Le Haut-fait n'est pas bugué , il a juste un fonctionnement légèrement différent , il suffit que les deux joueurs disposent du panier et clique sur son panier respectif , puis attendre que le coeur apparaisse pour manger le délice de lait.
