### ISSUE TITLE
recherche de donjon aléatoire

### ISSUE THREAD

**Issue by Tylias** [Naxxramas-Server/Bug-Tracker#23]
**Describe the bug** - **Description du bug**
Quand on tag pour une recherche de groupe, que ça proc et que quelqun refuse il peut y avoir un autre proc avec d'autres personnes avant que ceux du premier groupe retourne dans la recherche.

exemple : je tag aléa hm en dps, il manque 1 heal, j'attend 1 heure qu'il ait un heal qu tag, ça proc mais on dps refuse et je me retrouve le seul dps dans la liste d'attente parce qu'il y a un autre groupe qui a proc en prenant des dps qui ont attendu moins longtemps.

**To Reproduce** - **Comment reproduire**
-

**Expected behavior** - **Ce qu'il devrait se passer**
il faudrait que tout les joueurs retournent dans la liste d'attente avant de reproc une autre hm.

**Screenshots**
-

**Additional context** - **Informations complémentaires**
-

**Comment by Naxxramas-Server** [comment]
L'outil de donjon n'a aucun problème , il se peut que dans votre cas , un groupe avec un tank et/ou un heal ai pris votre place car ils sont prioritaires si ces fonctions sont manquantes.
