### ISSUE TITLE
Forge/Mine Dalaran

### ISSUE THREAD

**Issue by Kumik0** [Naxxramas-Server/Bug-Tracker#3]
**Describe the bug** - **Description du bug**
Il est pour l'instant impossible de forger et de fondre du minerai à la forge et le bâtiment mineur de Dalaran. Les deux emplacements semblent ne pas posséder de forge malgré la présence de "gob" dans les deux bâtiments cités.

**To Reproduce** - **Comment reproduire**
Les étapes pour reproduire le bug :
Tenter de fondre du minerai ou forger dans ces deux baitments

**Expected behavior** - **Ce qu'il devrait se passer**
L'on devrais pouvoir fondre du minerai ou forger dans ces deux bâtiments.

**Screenshots**
http://image.noelshack.com/fichiers/2018/51/4/1545332295-2018-12-20-1.png
http://image.noelshack.com/fichiers/2018/51/4/1545332293-2018-12-20.png

**Additional context** - **Informations complémentaires**
Bug très gênant qui nous empêche de fondre ou de monter nos métiers à Dalaran.

**Comment by Naxxramas-Server** [comment]
Une forge a été rajouté dans le bâtiment des forgerons , cependant la forge dans le bâtiment des mineurs permet bien de fondre ses minerais.
