### ISSUE TITLE
Trinket Oeuf de l'Essence Mortelle

### ISSUE THREAD

**Issue by Tyrranie** [Naxxramas-Server/Bug-Tracker#34]
Description du bug:

Le trinket Oeuf de l'Essence Mortelle, ID 40685, ne proc pas sur les soins prodigués par la spécialisation Démonologie du Démoniste.
L'effet devrait être déclenché sur les soins produits par la Gangrarmure ainsi que par les soins appliqués au familier après avoir infligé des dégâts.

Pour reproduire ce bug:

- Créer un démoniste
- Appliquer 2 points de talents sur la première ligne de la branche Démonologie: Fel Synergy
- Appliquer sur soi la Gangrarmure
- Invoquer un familier
- Se rendre sur un mob et faire attaquer votre familier jusqu'à ce qu'il perde de la vie
- Lancer des sorts de dégâts pour soigner votre familier

Lors des soins apportés par votre Gangrarmure, ou des soins produits sur votre familier, cela devrait déclencher l'effet du trinket.

https://image.noelshack.com/fichiers/2020/09/6/1583014419-wowscrnshot-022920-231034.jpg

Merci pour votre attention.

**Comment by Naxxramas-Server** [comment]
Le problème a été corrigé , merci de votre report
