### ISSUE TITLE
Suite de quête Tribu Frénécoeur/Les Oracles

### ISSUE THREAD

**Issue by viktortoli** [Naxxramas-Server/Bug-Tracker#4]
Pour lancer la suite de quête il faut tuer Poix, puis le Pisteur GekGek nous dit d'aller voir le Haut-Chaman Rekjek qui nous donne les quêtes à suivre, or, il manque la quête "Asticoter les poings-doux", donc la suite de quête ne se lance pas. 

Cette suite de quête est importante car d'une part elle permet de clean la zone pour le Haut-Fait Maître des Traditions, d'autre part car elle peut permettre d'obtenir une monture.

**Comment by Dreaxxx** [comment]
La quête asticoter les poings doux se prend en parlant a Gorekek , il faut utiliser les menottes de Gorekek que vous devez avoir dans votre inventaire.
Cette suite de quête n'est absolument pas buguée.

**Comment by Naxxramas-Server** [comment]
La quête asticoter les poings doux se prend en parlant a Gorekek , il faut utiliser les menottes de Gorekek que vous devez avoir dans votre inventaire.
Cette suite de quête n'est absolument pas buguée.

**Comment by viktortoli** [comment]
Oui, je viens de voir, à supprimer donc
