### ISSUE TITLE
[Quête] Le colosse de fer 

### ISSUE THREAD

**Issue by viktortoli** [Naxxramas-Server/Bug-Tracker#5]
**Describe the bug** - **Description du bug**
Le colosse de fer doit être battu en utilisant un Jormungar apprivoisé, or celui-ci fait trop de dégâts tandis que le Jormungar n'en fait que très peu, et ses sorts ont trop de CD

**To Reproduce** - **Comment reproduire**
Faire la quête "Le colosse de fer" aux Pics Foudroyés

**Expected behavior** - **Ce qu'il devrait se passer**
Le boss devrait être tuable

**Comment by Naxxramas-Server** [comment]
En effet , le Colosse a anormalement trop de vie.
Ceci sera réglé lors du prochain redémarrage du serveur.
