### ISSUE TITLE
[QUETE] [72] [Le vol du défenseur de Garde-Hiver](Part 4 of 8)

### ISSUE THREAD

**Issue by Kumik0** [Naxxramas-Server/Bug-Tracker#6]
**Describe the bug** - **Description du bug**
Il est actuellement impossible de "prendre" les villageois pour les emporter en lieu sur lorsque l'on chevauche le griffon de la quête.

**To Reproduce** - **Comment reproduire**
1. Prendre la quête  [72] [Le vol du défenseur de Garde-Hiver](Part 4 of 8)
2. Invoquer le griffon
3. Tenter d'attraper un villageois.

**Expected behavior** - **Ce qu'il devrait se passer**
L'on devrais pouvoir attraper les villageois et les emmener en lieu sur lorsque l'on chevauche le griffon

**Additional context** - **Informations complémentaires**
Add any other context about the problem here. (database link , etc ...)
Rajoutez des informations complémentaires sur le problème (lien base de donnée , etc...)

**Comment by Naxxramas-Server** [comment]
Bonjour Kumiko , merci du report , la quête sera analyser dans quelques jours.

**Comment by Naxxramas-Server** [comment]
Suite à différents tests , la quête est totalement fonctionnelle , vous avez du louper quelque chose.
