### ISSUE TITLE
[Livraison de lâche… En moins de 30 minutes, ou c'est gratuit]

### ISSUE THREAD

**Issue by Zupeuh** [Naxxramas-Server/Bug-Tracker#7]
[Livraison de lâche… En moins de 30 minutes, ou c'est gratuit]
Early Toundra quest (Bastion CHanteguerre)
Donnée par : Gardien Nork Frénésie-sanglante

But de la quête : Livrer un déserteur A2 à "croisée des chemins" (en gros une quête d'escorte)
Problème : Le PNJ que l'on doit livrer ne pop pas quand on lance la quête.

PS : Si j'peut me permettre, devoir s'inscrire sur un site pour repport un bug, ça va en décourager plus d'un, surtout pour des petits bugs.

Bon courage

**Comment by Naxxramas-Server** [comment]
Merci pour votre report , nous analyserons ce probleme sous peu.
Pour le bugtracker,  c'est un bon moyen d'avoir un suivis malgré ce fait.

**Comment by Naxxramas-Server** [comment]
Suite à différents tests , la quête est totalement faisable sur le serveur , il suffit de reparler au Gariden Nork pour lui demander de nous laisser un déserteur à emmener.
