### ISSUE TITLE
[QUETE]  [77] [Le sauveur des Marchemousses]

### ISSUE THREAD

**Issue by Kumik0** [Naxxramas-Server/Bug-Tracker#8]
**Describe the bug** - **Description du bug**
Il est actuellement impossible de parler aux PNJ "Victime Marchemousse" afin de les sauver pour accomplir la quête.

A notter aussi que les victimes sont sensé être tiré par les PNJ "Cadavre chancreux" au bout d'une chaine, ce qui n'est pas le cas actuellement.

**To Reproduce** - **Comment reproduire**
Les étapes pour reproduire le bug :
1. Prendre la quête  [77] [Le sauveur des Marchemousses]
2. Constater

**Expected behavior** - **Ce qu'il devrait se passer**
https://www.youtube.com/watch?v=hd3BcCSDNr4&feature=youtu.be

On devrais pouvoir leur parler afin de les sauver

**Screenshots**
https://www.youtube.com/watch?v=hd3BcCSDNr4&feature=youtu.be

**Additional context** - **Informations complémentaires**

**Comment by Naxxramas-Server** [comment]
Merci pour votre report  , nous analyserons ceci d'ici quelques jours.

**Comment by Kumik0** [comment]
Bonjour, on souci récurrent qui fais bug plusieurs quêtes qui en fait ne sont pas réellement bug, c'est que la faction pour lequel on fais la quête se met "en guerre" toute seule ce qui ne devrais pas être le cas.

Ce qui provoque certains souci, comme par exemple interagir avec des pnj d'une certaine faction pour une quête.

Comme j'ai eu le cas pour cette quête.

**La quête fonctionne donc parfaitement** _le problème viens du "en guerre" auto des réputations_, le même souci se produit avec les fils d'hodir.

**Comment by Naxxramas-Server** [comment]
La quête n'a pas de bug , mais en effet , si la faction "Oracle" est cochée en guerre dans le panneau des Réputation , il est impossible de parler aux victimes.
