### ISSUE TITLE
Paladin : Ratio Puissance des sorts Horion sacré

### ISSUE THREAD

**Issue by Steinsgate00** [Naxxramas-Server/Bug-Tracker#9]
L'horion sacré ne se scale pas correctement sur la puissance des sorts. Les ratios appliqués sont trop bas.

**Comment reproduire**

1) Prendre un paladin avec horion sacré (j'utilisais le rang 4 pour mes test qui produit entre 693 et 749 dégats ou 1061 et 1149 de heal.
2) Equiper une ou plusieurs pièces avec de la puissance des sorts (j'avais un montant de 555 puissance des sorts)
3) Lancer Horion sacré de nouveaux et constater les dégats/soins  : Après une 30aine de lancers de sorts on peut observer que le ratio pour les soins s'applique correctement (fourchette observée entre 1512 et 1596) en revanche le ratio pour les dégats n'est pas bon (fourchette observée entre 944 et 982)

Petit calcul rapide : 
Moyenne dégats de base = (693+749)/2 = 721
Moyenne dégats = (944+982)/2 = 963
Dégats bonus du à la puissance des sorts = 963-721 = 242
Calcul du ratio appliqué = (100*242)/555 -100 = 43.6%

**Ce qu'il devrait se passer**
Selon la DB il est sensé scale à 81% pour les soins, et 100% pour les dégats. 
Avec 555 PS on est sensé obtenir 1248-1304 dégats (on en est loin..) / 1510-1598 (ça en revanche ça marche niquel ! )

N'ayant pas de Paladin plus haut niveau que 68 pour le moment je n'ai pas pu tester sur les rang supérieur de l'horion sacré mais en toute logique le ratio est sensé être le même sur tous les rangs du sort. 
(à noter que tous ces calculs ont été fait hors bonus de dégats apporté par les points de talents pour avoir des stats au plus juste)

Lien de la database pour le scaling heal de l'horion sacré 
https://wotlk.evowow.com/?spell=48821

Lien de la database pour le scaling dégat de l'horion sacré
https://wotlk.evowow.com/?spell=48823

Cordialement, Steinsgate le mageladin qui vous veut du bien ;) !

**Comment by Naxxramas-Server** [comment]
Merci du report , nous analyserons ceci d'ici quelques jours.

**Comment by Naxxramas-Server** [comment]
Le sort a été corrigé et sera effectif dès le prochain redémarrage du serveur.
